services:
  sas_conversions:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "
      cd /root/sas_conversions_devel/src/
      && ls .
      && colcon build
      && source install/setup.bash
      && ros2 run sas_conversions sas_conversions_example_readme"