FROM murilomarinho/sas:jazzy
LABEL authors="murilomarinho"
SHELL ["/bin/bash", "-c"]
ENV BASH_ENV="/etc/bash_env"

RUN sudo apt-get update && sudo apt-get upgrade -y
RUN sudo sudo dpkg -r --force-depends ros-jazzy-sas-conversions
RUN mkdir -p /root/sas_common_devel/src/