#pragma once
/*
# Copyright (c) 2016-2023 Murilo Marques Marinho
#
#    This file is part of sas_conversions.
#
#    sas_conversions is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    sas_conversions is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with sas_conversions.  If not, see <https://www.gnu.org/licenses/>.
#
# ################################################################
#
#   Author: Murilo M. Marinho, email: murilomarinho@ieee.org
#
# ################################################################*/

#include<dqrobotics/DQ.h>

#include<rclcpp/rclcpp.hpp>

#include<std_msgs/msg/header.hpp>

#include<geometry_msgs/msg/point.hpp>
#include<geometry_msgs/msg/point_stamped.hpp>
#include<geometry_msgs/msg/quaternion.hpp>
#include<geometry_msgs/msg/pose.hpp>
#include<geometry_msgs/msg/pose_stamped.hpp>
#include<geometry_msgs/msg/wrench.hpp>
#include<geometry_msgs/msg/wrench_stamped.hpp>
#include<geometry_msgs/msg/twist.hpp>

using namespace DQ_robotics;

namespace sas
{
///*********************************
///   DQ <-> geometry_msgs::Point
///*********************************
/**
 * @brief Convert a geometry_msgs::msg::Point to a DQ representing a pure translation.
 *
 * The returned DQ encodes the point as a pure translation (no rotation).
 *
 * @param msg The input geometry_msgs::msg::Point message.
 * @return DQ A dual quaternion representing the point as a translation.
 */
DQ geometry_msgs_point_to_dq(const geometry_msgs::msg::Point& msg);

/**
 * @brief Convert a DQ (pure quaternion) to a geometry_msgs::msg::Point.
 *
 * @param dq The input pure quaternion.
 * @return geometry_msgs::msg::Point The corresponding point message.
 */
geometry_msgs::msg::Point dq_to_geometry_msgs_point(const DQ& dq);

/**
 * @brief Convert a geometry_msgs::msg::PointStamped to a DQ (pure quaternion).
 *
 * The returned DQ encodes the stamped point as a translation (no rotation).
 * The header/time information is discarded by this conversion.
 *
 * @param msg The input geometry_msgs::msg::PointStamped message.
 * @return DQ A dual quaternion representing the stamped point as a translation.
 */
DQ geometry_msgs_point_stamped_to_dq(const geometry_msgs::msg::PointStamped& msg);

/**
 * @brief Convert a DQ (translation-only) to a geometry_msgs::msg::PointStamped.
 *
 * The returned PointStamped contains only the translation encoded in the DQ;
 * no header/time information is generated by this helper.
 *
 * @param dq The input dual quaternion.
 * @return geometry_msgs::msg::PointStamped The corresponding stamped point message.
 */
geometry_msgs::msg::PointStamped dq_to_geometry_msgs_point_stamped(const DQ& dq);

///*********************************
///   DQ <-> geometry_msgs::Pose
///*********************************
/**
 * @brief Convert a geometry_msgs::msg::Pose to a DQ representing pose (rotation + translation).
 *
 * The orientation (quaternion) and position from the Pose message are
 * encoded into the returned dual quaternion.
 *
 * @param msg The input geometry_msgs::msg::Pose message.
 * @return DQ Dual quaternion representing the pose.
 */
DQ geometry_msgs_pose_to_dq(const geometry_msgs::msg::Pose& msg);

/**
 * @brief Convert a DQ representing a pose to a geometry_msgs::msg::Pose.
 *
 * The rotational and translational components of the DQ are extracted and
 * placed into the Pose message.
 *
 * @param dq The input dual quaternion representing a pose.
 * @return geometry_msgs::msg::Pose The corresponding Pose message.
 */
geometry_msgs::msg::Pose dq_to_geometry_msgs_pose(const DQ& dq);

/**
 * @brief Convert a geometry_msgs::msg::PoseStamped to a DQ representing pose.
 *
 * Header information (timestamp/frame_id) is not preserved by the DQ output.
 *
 * @param msg The input geometry_msgs::msg::PoseStamped message.
 * @return DQ Dual quaternion representing the stamped pose.
 */
DQ geometry_msgs_pose_stamped_to_dq(const geometry_msgs::msg::PoseStamped& msg);

/**
 * @brief Convert a DQ representing a pose to a geometry_msgs::msg::PoseStamped.
 *
 * The returned PoseStamped contains the translation and rotation from the DQ.
 * The header is populated with the current time, but no frame_id is set by this helper.
 *
 * @param dq The input dual quaternion representing a pose.
 * @return geometry_msgs::msg::PoseStamped The corresponding stamped Pose message.
 */
geometry_msgs::msg::PoseStamped dq_to_geometry_msgs_pose_stamped(const DQ& dq);

///*********************************
///   DQ <-> geometry_msgs::Quaternion
///*********************************
/**
 * @brief Convert a geometry_msgs::msg::Quaternion to a DQ representing rotation.
 *
 * The resulting DQ contains the rotation represented by the input quaternion
 * (no translation).
 *
 * @param msg The input geometry_msgs::msg::Quaternion message.
 * @return DQ Dual quaternion representing the rotation.
 */
DQ geometry_msgs_quaternion_to_dq(const geometry_msgs::msg::Quaternion& msg);

/**
 * @brief Convert a DQ to a geometry_msgs::msg::Quaternion.
 *
 * The rotational component of the DQ is extracted and returned as a
 * geometry_msgs::msg::Quaternion. If the input DQ contains translation,
 * it is ignored.
 *
 * @param dq The input dual quaternion.
 * @return geometry_msgs::msg::Quaternion The extracted orientation.
 */
geometry_msgs::msg::Quaternion dq_to_geometry_msgs_quaternion(const DQ& dq);

///*********************************
///   DQ <-> geometry_msgs::Wrench
///*********************************
/**
 * @brief Convert a geometry_msgs::msg::Wrench to DQ representations of force and torque.
 *
 * The force and torque vectors from the Wrench message are converted to
 * pure-vector DQs and stored in the provided output parameters.
 *
 * @param msg The input geometry_msgs::msg::Wrench message.
 * @param[out] force DQ that will be set to represent the force vector.
 * @param[out] torque DQ that will be set to represent the torque vector.
 */
void geometry_msgs_wrench_to_dq(const geometry_msgs::msg::Wrench& msg, DQ& force, DQ& torque);

/**
 * @brief Convert force and torque represented as DQs to a geometry_msgs::msg::Wrench.
 *
 * The translational components of the input DQs are used to populate the
 * Wrench's force and torque vectors.
 *
 * @param force DQ representing the force vector.
 * @param torque DQ representing the torque vector.
 * @return geometry_msgs::msg::Wrench The resulting Wrench message.
 */
geometry_msgs::msg::Wrench dq_to_geometry_msgs_wrench(const DQ& force, const DQ& torque);

/**
 * @brief Convert a geometry_msgs::msg::WrenchStamped to DQ representations of force and torque.
 *
 * The header/timestamp is ignored; only the wrench vectors are converted.
 *
 * @param msg The input geometry_msgs::msg::WrenchStamped message.
 * @param[out] force DQ that will be set to represent the force vector.
 * @param[out] torque DQ that will be set to represent the torque vector.
 */
void geometry_msgs_wrench_stamped_to_dq(const geometry_msgs::msg::WrenchStamped& msg, DQ& force, DQ& torque);

/**
 * @brief Convert force and torque DQs to a geometry_msgs::msg::WrenchStamped.
 *
 * The returned WrenchStamped contains only the force/torque vectors; no
 * header/time information is populated by this helper.
 *
 * @param force DQ representing the force vector.
 * @param torque DQ representing the torque vector.
 * @return geometry_msgs::msg::WrenchStamped The resulting stamped wrench message.
 */
geometry_msgs::msg::WrenchStamped dq_to_geometry_msgs_wrench_stamped(const DQ& force, const DQ& torque);

///*********************************
///   DQ <-> geometry_msgs::Twist
///*********************************
/**
 * @brief Convert a geometry_msgs::msg::Twist to DQ representations of linear and angular velocities.
 *
 * The linear and angular vectors from the Twist message are converted to
 * pure-vector DQs and stored in the provided output parameters.
 *
 * @param msg The input geometry_msgs::msg::Twist message.
 * @param[out] linear DQ that will be set to represent the linear velocity.
 * @param[out] angular DQ that will be set to represent the angular velocity.
 */
void geometry_msgs_twist_to_dq(const geometry_msgs::msg::Twist& msg, DQ& linear, DQ& angular);

/**
 * @brief Convert linear and angular velocities represented as DQs to a geometry_msgs::msg::Twist.
 *
 * The translational components of the input DQs are used to populate the
 * Twist's linear and angular vectors.
 *
 * @param linear DQ representing the linear velocity.
 * @param angular DQ representing the angular velocity.
 * @return geometry_msgs::msg::Twist The resulting Twist message.
 */
geometry_msgs::msg::Twist dq_to_geometry_msgs_twist(const DQ& linear, const DQ& angular);

}

